config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[show]
  resources :bank_accounts do
    get "movements", to: "movements#bank_movements"
  end
  resources :categories, except: %i[show]
  resources :movements, only: %i[index]
  get "instructions", to: "pages#instructions"
  get "statistics", to: "movements#statistics"
end

app/models/movement.rb
class Movement < ApplicationRecord
  belongs_to :bank_account
  belongs_to :user
  # belongs_to :category

  include PgSearch::Model
  pg_search_scope :search_by_description,
    against: [ :description ],
    using: {
      tsearch: { prefix: true }
    }

  validates :fintoc_id, :amount, :description, :currency, presence: true
  validates :fintoc_id, uniqueness: true
end

app/controllers/movements_controller.rb
require "json"
require "open-uri"
require "date"

class MovementsController < ApplicationController

  def index
    @banks = BankAccount.where(user_id: current_user.id)
    @movements = Movement.where(user_id: current_user.id).order(post_date: :desc)
    @categories = Category.all
    if params[:bank].present? && params[:bank] != 'Todos'
      bank = BankAccount.find_by(bank: params[:bank])
      @movements = Movement.where(bank_account_id: bank.id, user_id: current_user.id)
    end
    if params[:bank].present? && params[:bank] == 'Todos'
      @movements = Movement.where(user_id: current_user.id).order(post_date: :desc)
    end
    if params[:category].present? && params[:category] != 'Todas'
      category = Category.find_by(name: params[:category])
      @movements = Movement.where(category_id: category.id, user_id: current_user.id)
    end
    if params[:category].present? && params[:category] == 'Todas'
      @movements = Movement.where(user_id: current_user.id).order(post_date: :desc)
    end
    if params[:quantity].present? && params[:quantity] != 'Todos'
      @movements = @movements.limit(params[:quantity])
    end
    if params[:category].present? && params[:category] == 'Todas'
      @movements = Movement.where(user_id: current_user.id).order(post_date: :desc)
    end
    if params[:query].present?
      @movements = Movement.where(user_id: current_user.id).search_by_description(params[:query])
    end
  end

  def bank_movements
    @bank = BankAccount.find(params[:bank_account_id])
    @movements = Movement.where(bank_account_id: @bank.id, user_id: current_user.id)
    if params[:query].present?
      @movements = Movement.where(user_id: current_user.id).search_by_description(params[:query])
    end
    if params[:quantity].present? && params[:quantity] != 'Todos'
      @movements = @movements.limit(params[:quantity])
    end
  end

  def statistics
    @banks = BankAccount.where(user_id: current_user.id)
    @movements = Movement.where(user_id: current_user.id)

  end
end

app/views/movements/bank_movements.html.erb
<div class='container'>
<br>
<div class="d-flex justify-content-between align-items-center">
  <h1>Movimientos <%= @bank.bank %></h1>
  <div class="btn-change-name">
  <%= link_to "Cambia tu nombre de cuenta", edit_bank_account_path(@bank), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#exampleModal'} %>

</div> <div> <%= link_to "Borrar cuenta",
              bank_account_path(@bank),
              method: :delete,
              class: "text-danger",
              data: { confirm: "¿Estás seguro que quieres eliminar esta cuenta?" } %>
  </div>
</div>
<h4><%= @bank.name %></h4>
<br>
<%= form_tag bank_account_movements_path, method: :get do %>
<div class="d-flex justify-content-between align-items-center">
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Encuentra un movimiento"
  %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
</div>
<% end %>

<br>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">
      <% quantity= [10, 20, 30] %>
      <%= form_with(url: bank_account_movements_path, method: :get, local: true, remote: true) do |f| %>
        <%= f.select(:quantity, quantity.push('Todos'), {prompt: '#'}, onchange: 'this.form.submit()', class: 'form-select form-select-sm')%>
      <% end %>
      </th>
      <th scope="col">Fecha</th>
      <th scope="col">Monto</th>
      <th scope="col">Descripcion</th>
    </tr>
  </thead>
  <tbody>


<%@movements.each_with_index do |movement, i|%>
  <tr>
    <th scope="row"><%= i+1 %></th>
    <td><%= movement['post_date'].to_date%></td>
    <td><%= number_to_currency(movement['amount'], :precision => 0, :delimiter =>'.')%></td>
    <td><%= movement['description']%></td>
  </tr>
<% end %>


  </tbody>
</table>
<%= link_to "Volver", bank_accounts_path, class: "btn btn-gradient" %>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edita tu nombre de cuenta</h5>
        <button type="button" class="close btn-cierre" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for(@bank) do |f| %>
          <br>
          <%= f.input :name, :label => 'Nombre de tu cuenta' %>
          <%= f.button :submit, "Cambiar nombre", class: 'btn-submit'%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/movements/index.html.erb
<br>
<div class='container'>
<h1>Movimientos</h1>
<br>


<%= form_tag movements_path, method: :get do %>
  <div class="d-flex justify-content-between align-items-center">
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Encuentra un movimiento"
  %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
  </div>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">
      <% quantity= [10, 20, 30] %>
      <%= form_with(url: movements_path, method: :get, local: true, remote: true) do |f| %>
        <%= f.select(:quantity, quantity.push('Todos'), {prompt: '#'}, onchange: 'this.form.submit()', class: 'form-select form-select-sm')%>
      <% end %>
      </th>
      <br>
      <th scope="col">
        <% bank_array = @banks.map do |bank| %>
          <% bank.bank %>
        <% end %>
        <%= form_with(url: movements_path, method: :get, local: true) do |f| %>
          <%= f.select(:bank, bank_array.push('Todos'), {prompt: 'Filtrar por banco'}, onchange: 'this.form.submit()', class: 'form-select form-select-sm')%>
        <% end %>
        </th>
      <th scope="col">Fecha</th>
      <th scope="col">Monto</th>
      <th scope="col">Descripción</th>
      <th scope="col">Categorías</th>
    </tr>
  </thead>
  <tbody>
  <% @movements.each_with_index do |movement, i| %>
  <tr>
    <th scope="row"><%= i+1 %></th>
    <td><%= BankAccount.where(id: movement.bank_account_id).first.bank %></td>
    <td><%= movement['post_date'] %></td>
    <td><%= number_to_currency(movement['amount'], :precision => 0, :delimiter =>'.') %></td>
    <td><%= movement['description'] %></td>
    <% user_categories = current_user.categories.map do |category| %>
      <% category.name %>
    <% end %>
    <td><%= simple_form_for Movement.new do |f| %>
          <%= f.input :category_id, collection: user_categories, label: false, selected: movement.category_id %>
        <% end %>
    </td>
  </tr>
  <% end %>
  </tbody>
</table>
<%= link_to "Volver", bank_accounts_path, class: "btn btn-gradient" %>
</div>

app/views/movements/statistics.html.erb
<br>
<div class="row">
  <div class="col-sm-9">
    <div class="card text-center">
      <div class="card-header">
        Todos los bancos
      </div>
      <div class="card-body">

        <%= line_chart @banks.map { |bank|
          movements = Movement.where(user_id: current_user.id, bank_account_id: bank.id)
            {name: bank.bank, data: movements.group_by_day(:post_date).sum(:amount)}
          }, thousands: ".", prefix: "$", min: -30000000, max: 30000000%>
          <br>
        <a href="<%= movements_path %>" class="btn btn-primary btn-sm">Ver detalles</a>
      </div>
    </div>
    <br>
    <% @banks.each do |bank| %>
      <div class="card text-center">
        <div class="card-header">
          <%= bank.bank %>
        </div>
        <div class="card-body">
          <% movements =  Movement.where(user_id: current_user.id, bank_account_id: bank.id)%>
          <%= line_chart movements.group_by_day(:post_date).sum(:amount), thousands: ".", prefix: "$", min: -30000000, max: 30000000 %>
          <br>
          <a href="<%= bank_account_movements_path(bank) %>" class="btn btn-primary btn-sm">Ver detalles</a>
        </div>
      </div>
      <br>
    <% end %>
    <%= link_to "Volver", bank_accounts_path, class: "btn btn-gradient" %>
  </div>
</div>