config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[show]
  resources :bank_accounts do
    get "movements", to: "movements#bank_movements"
  end
  resources :categories, except: %i[show]
  resources :movements, only: %i[index]
  get "instructions", to: "pages#instructions"
  get "statistics", to: "movements#statistics"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
    <div class="footer-basic">
        <footer>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="#">Home</a></li>
                <li class="list-inline-item"><a href="#">Servicios</a></li>
                <li class="list-inline-item"><a href="#">Acerca de Le Wallet</a></li>
                <li class="list-inline-item"><a href="#">Términos y condiciones</a></li>
                <li class="list-inline-item"><a href="#">Seguridad y privacidad</a></li>
            </ul>
            <p class="copyright">Le Wallet © 2022</p>
        </footer>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "logo.png" %>
      <strong class="text-lwd">Le Wallet Digital</strong>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in?  %>
          <li class="nav-item active">
            <%= link_to "Balances", bank_accounts_path, class: "nav-link" %>
          </li>
          <% accounts = BankAccount.where(user_id: current_user).size %>
          <% if accounts != 0 %>
          <li class="nav-item">
            <%= link_to "Movimientos", movements_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Estadísticas", statistics_path, class: "nav-link" %>
          </li>
          <% end %>
          <li class="nav-item">
            <%= link_to "Categorías", categories_path, id: "modals", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Perfil", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Ayuda", "#", class: "dropdown-item" %>
              <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Inicia sesión", new_user_session_path, class: "bn3637 bn37" %>
          </li>
          <li class="nav-item">
            <%= link_to "Crear cuenta", new_user_registration_path, class: "bn3637 bn37 b" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<script>$("#modals").on.click(location.reload())</script>