config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[show]
  resources :bank_accounts do
    get "movements", to: "movements#bank_movements"
  end
  resources :categories, except: %i[show]
  resources :movements, only: %i[index]
  get "instructions", to: "pages#instructions"
  get "statistics", to: "movements#statistics"
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  belongs_to :user
  has_many :movements, dependent: :destroy

  validates :pk, :sk, :link, :bank, presence: true
  validates :name, uniqueness: true
end

app/controllers/bank_accounts_controller.rb
require 'open-uri'
require 'json'

class BankAccountsController < ApplicationController
  before_action :set_bank, only: %i[show edit update destroy]

  def index
    @banks = BankAccount.where(user_id: current_user.id)
    @movements = Movement.where(user_id: current_user.id).limit(10).order(post_date: :desc)
    @balance = @banks.map do |bank|
      url = "https://api.fintoc.com/v1/accounts/#{bank.fintoc_id}?link_token=#{bank.link}"
      user_serialized = URI.open(url, "Authorization" => bank.sk).read
      user = JSON.parse(user_serialized)
      user['balance']['available']
    end
    @banks.each do |bank|
      url = "https://api.fintoc.com/v1/accounts/#{bank.fintoc_id}/movements?link_token=#{bank.link}"
      user_serialized = URI.open(url, "Authorization" => bank.sk).read
      movements = JSON.parse(user_serialized)
      movements.each do |movement|
        movement = Movement.new(user_id: current_user.id, category_id: 1, bank_account_id: bank.id, fintoc_id: movement['id'], amount: movement['amount'],
                                 description: movement['description'], currency: movement['currency'], post_date: movement['post_date'])
        movement.save
      end
    end
  end

  def new
    @bank = BankAccount.new
  end

  def create
    @bank = BankAccount.new(bank_params)
    @bank.user_id = current_user.id
    url = "https://api.fintoc.com/v1/accounts/?link_token=#{@bank.link}"
    user_serialized = URI.open(url, "Authorization" => @bank.sk).read
    user = JSON.parse(user_serialized)
    @bank.account_number = user.first['number']
    @bank.account_type = user.first['official_name']
    @bank.fintoc_id = user.first['id']
    if @bank.save
      # url = "https://api.fintoc.com/v1/accounts/#{@bank.fintoc_id}/movements?link_token=#{@bank.link}"
      # user_serialized = URI.open(url, "Authorization" => @bank.sk).read
      # movements = JSON.parse(user_serialized)
      # movements.each do |movement|
      #   movement = Movement.new(user_id: current_user.id, category_id: 1, bank_account_id: @bank.id, fintoc_id: movement['id'], amount: movement['amount'],
      #                            description: movement['description'], currency: movement['currency'], post_date: movement['post_date'])
      #   movement.save
      # end
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @bank.update(bank_params)
      redirect_to bank_accounts_path
    else
      render 'edit'
    end
  end

  def destroy
    @bank.destroy
    redirect_to bank_accounts_path
  end

  private

  def bank_params
    params.require(:bank_account).permit(:name, :sk, :pk, :link, :bank)
  end

  def set_bank
    @bank = BankAccount.find(params[:id])
  end
end

app/views/bank_accounts/index.html.erb
<br>
<% total = @balance.sum %>
<div class="container">
  <div>
    <h3><%="Hola #{current_user.name}!"%></h3>
    <br>
    <h1><strong><%= number_to_currency(total, :precision => 0, :delimiter => '.') %></strong></h1>
    <h6 class="text-gray">TOTAL</h6>
    <br>
  </div>
  <div class="cards">
  <% @banks.each_with_index do |bank, index| %>
    <div class="card-balance" style="background-color: #0D6EFD">
      <h3><%= link_to bank.bank, bank_account_movements_path(bank), class: "text-white"%></h3>
      <h6><%= "#{bank.account_type} #{bank.account_number}" %></h6>
      <h4><%= bank.name %></h5>
      <h2><%= number_to_currency(@balance[index], :precision => 0, :delimiter => '.') %></h2>
      <br>
    </div>
  <% end %>
  <div class="card-balance" style="justify-content: center; background-color: #0D6EFD">
      <%= link_to "+ Agrega un nuevo banco", new_bank_account_path, class: "text-white" %>
    </div>
  </div>
<br><br>
<% accounts = BankAccount.where(user_id: current_user).size %>
<% if accounts != 0 %>
<div class="d-flex justify-content-between align-items-center">
  <h1>Últimos movimientos</h1>
  <%= link_to 'Ver todos los movimientos', movements_path %>
</div>
<br>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Banco</th>
      <th scope="col">Fecha</th>
      <th scope="col">Monto</th>
      <th scope="col">Descripción</th>
      <th scope="col">Categoría</th>
    </tr>
  </thead>
  <tbody>
  <% @movements.each_with_index do |movement, i| %>
  <tr>
    <th scope="row"><%= i+1 %></th>
    <td><%= BankAccount.where(id: movement.bank_account_id).first.bank %></td>
    <td><%= movement['post_date'] %></td>
    <td><%= number_to_currency(movement['amount'], :precision => 0, :delimiter =>'.') %></td>
    <td><%= movement['description'] %></td>
    <td><%= Category.where(id: movement.category_id).first.name %></td>
  </tr>
  <% end %>
  </tbody>
</table>
<% end %>
</div>

app/views/bank_accounts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-4 col-sm-offset-4">
      <div class="form-devise">
        <br>
        <%= link_to "Cómo crear links y API keys ", instructions_path %>
        <% banks = ['Banco de Chile', 'Santander', 'Itaú', 'BICE', 'Scotiabank', 'BCI', 'Banco Estado', 'Security'] %>
        <%= simple_form_for(@bank) do |f| %>
          <br>
          <%= f.input :name, :label => 'Nombre de tu cuenta' %>
          <%= f.input :bank, collection: banks %>
          <%= f.input :link %>
          <%= f.input :pk %>
          <%= f.input :sk %>
          <%= f.button :submit, "Crear cuenta", class: 'btn-submit'%>
        <% end %>
        <%= link_to "Volver", :back, class: "btn btn-gradient" %>
      </div>
    </div>
  </div>
</div>