config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[show]
  resources :bank_accounts do
    get "movements", to: "movements#bank_movements"
  end
  resources :categories, except: %i[show]
  resources :movements, only: %i[index]
  get "instructions", to: "pages#instructions"
  get "statistics", to: "movements#statistics"
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :movements
  has_many :user_categories, dependent: :destroy

  validates :name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[edit update destroy]

  def index
    @categories = Category.all
    @category = Category.new

  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      @userCategory = UserCategory.new
      @userCategory.user = current_user
      @userCategory.category = @category
      @userCategory.save
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/views/categories/_form.html.erb
<%= simple_form_for(category) do |f| %>
  <div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Menú categorías</h5>
    <button type="button" class="close btn-cierre" data-bs-dismiss="modal">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
      <h4>Crea una nueva categoría</h4>
        <%= f.input :name, :label => 'Nombre' %>
  </div>
  <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
        <button type="submit" class="btn btn-primary">Crear</button>
      </div>
<% end %>

app/views/categories/_form2.html.erb
<%= simple_form_for(category) do |f| %>
<div class="modal-content">
  <div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Menú categorías</h5>
    <button type="button" class="close btn-cierre" data-bs-dismiss="modal">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
      <h4>Edita esta categoría</h4>
        <%= f.input :name, :label => 'Nombre' %>
  </div>
  <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
        <button type="submit" class="btn btn-primary">Actualizar</button>
      </div>
</div>
<% end %>

app/views/categories/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-6">
      <div class="form-devise">
        <h2>Edita esta categoría</h2>
        <%= simple_form_for(@category) do |f| %>
          <%= f.input :name, :label => 'Nombre de la categoría' %>
          <%= f.button :submit, 'Actualizar categoría', class: 'btn-submit' %>
          <%= link_to "Volver", :back, class: "btn btn-gradient" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/categories/edit.js.erb
$('#editModal .modal-content').html('<%= j render "form2", category: @category %>');
$('#editModal').modal('show');

app/views/categories/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-8">
      <div class="form-devise">
        <br>
        <h2>Categorías</h2>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Categoría</th>
              <th scope="col" class="text-end">Editar/Borrar</th>
            </tr>
          </thead>
          <tbody>
          <% current_user.categories.each_with_index do |category, index| %>
            <tr>
              <td scope="row"><%= index + 1 %></td>
              <td><%= category.name %></td>
              <td class="text-end"><%= link_to "", edit_category_path(category), remote: true, class: "fa fa-edit" %>
              <%= link_to "",
                      category_path(category),
                      method: :delete,
                      class: "fa fa-trash ms-3 text-danger",
                      data: { confirm: "¿Quieres eliminar esta categoría?" } %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <br>
        <%= link_to "Crear nueva categoría", new_category_path, {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#exampleModal', class: "nav-link btn-ctgy"} %>
        <%= link_to "Volver", bank_accounts_path, class: "btn btn-gradient" %>
      </div>
    </div>
  </div>
</div>

<!-- Modal new -->

<div class="modal fade" id="newModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

    </div>
  </div>
</div>

<!-- Modal edit -->

<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

    </div>
  </div>
</div>

app/views/categories/new.js.erb
$('#newModal .modal-content').html('<%= j render "form", category: @category %>');
$('#newModal').modal('show');